on:
  schedule:
    # runs once a week on sunday
    - cron: "55 23 * * 0"

jobs:
  # This workflow contains a single job called "traffic"
  traffic:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: "main"

    # Calculates traffic and clones and stores in CSV file
    - name: GitHub traffic
      uses: sangonzal/repository-traffic-action@v.0.1.6
      env:
        TRAFFIC_ACTION_TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }}

    # Commits files to repository
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Santiago Gonzalez
        message: "GitHub traffic"
        add: "./traffic/*"
        ref: "main"  # commits to branch "traffic"
    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.TRAFFIC_ACTION_TOKEN }}
      with:
        source_file: 'traffic'
        destination_repo: 'jzemmels/trafficMonitor'
        destination_folder: 'impressions-traffic'
        user_email: 'jzemmels@iastate.edu'
        user_name: 'jzemmels'
        commit_message: 'Push impressions traffic data'
    - name: Remove File
      uses: JesseTG/rm@v1.0.3
      with:
        path: ./traffic/
